#!/usr/bin/zsh

alias reload='source ~/.zshrc'
alias k=kubectl
alias dstop='docker stop $(docker ps -a -q) 2>/dev/null'
alias cat='bat'
alias ccat='cat'
alias lg='lazygit'
alias ls='exa -l'
alias l='exa'
alias watch='viddy'
alias cava='cava -p ~/.config/themes/cava'
alias pkg-find='paru -Ql'
alias neo='neofetch'
alias tree='cbonsai'
alias p='paru'

alias gp='git push'

alias dotfiles='cd ~/dotfiles'
alias jobfiles='cd ~/jobfiles'
alias build-dwm='cd ~/.config/dwm && sudo make clean install && cd -'
alias build-dwmblocks='cd ~/.config/dwmblocks && sudo make clean install && cd -'
alias reload-wallpaper='feh --no-fehbg --bg-scale ~/.config/themes/wallpaper.png'
