#!/bin/bash

PS3='Packages sets - enter choice: '
options=("Home" "Dev" "Games" "General" "Editing" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Home")
            paru -Sy --needed coolero betterdiscord-installer-bin qbittorrent-qt5
            break
            ;;
        "Dev")
            paru -Sy --needed keepassxc remmina freerdp docker docker-compose pycharm-professional webstorm webstorm-jre python python-pip\
            npm slack-desktop gparted gnome-disk-utility etcher-bin ventoy-bin kubectl helm kubectx kubens k9s kubetail dive-bin

            sudo groupadd docker
            sudo usermod -aG docker "$USER"
            sudo systemctl enable docker.service
            sudo systemctl start docker.service
            sudo systemctl enable containerd.service
            sudo systemctl start containerd.service
            break
            ;;
        "Games")
            paru -Sy --needed steam lutris bottles nvidia-settings

            sudo pacman -S --needed wine-staging giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls \
            mpg123 lib32-mpg123 openal lib32-openal v4l-utils lib32-v4l-utils libpulse lib32-libpulse libgpg-error \
            lib32-libgpg-error alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo \
            sqlite lib32-sqlite libxcomposite lib32-libxcomposite libxinerama lib32-libgcrypt libgcrypt lib32-libxinerama \
            ncurses lib32-ncurses ocl-icd lib32-ocl-icd libxslt lib32-libxslt libva lib32-libva gtk3 \
            lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs vulkan-icd-loader lib32-vulkan-icd-loader

            break
            ;;
        "General")
            paru -Sy --needed firefox discord chromium spotify
            break
            ;;
        "Editing")
            paru -Sy --needed gimp inkscape krita
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
