#!/bin/bash

PS3='Packages sets - enter choice: '
options=("Home" "Dev" "Games" "General" "Editing" "Nvidia" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Home")
            paru -Sy coolero discord betterdiscord-installer qbittorrent
            break
            ;;
        "Dev")
            paru -Sy keepassxc remmina freerdp docker docker-compose pycharm-professional webstorm python \
            slack-desktop gparted gnome-disk-utility etcher-bin ventoy-bin

            sudo groupadd docker
            sudo usermod -aG docker "$USER"
            sudo systemctl enable docker.service
            sudo systemctl enable containerd.service
            break
            ;;
        "Games")
            paru -Sy steam lutris bottles
            break
            ;;
        "General")
            paru -Sy firefox chromium spotify spotify-tui
            break
            ;;
        "Editing")
            paru -Sy gimp inkscape krita
            break
            ;;
        "Nvidia")
            paru -Sy nvidia nvidia-utils nvidia-settings
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
