#!/bin/bash

sudo pacman -S --needed base-devel xorg xorg-xinit xorg-xrdb picom archlinux-keyring alacritty sxhkd feh dex

# Install aur helper -- paru
git clone https://aur.archlinux.org/paru.git
cd paru && makepkg -si
cd .. && rm -rf paru

# Install packages
~/dotfiles/packages
chsh -s /bin/zsh

mkdir .config
~/dotfiles/bin/copy-dotfiles

sudo systemctl enable ly.service
sudo systemctl enable bluetooth.service
sudo systemctl --user start dunst.service

cd ~/.config/dwm && sudo make install
cd ~/.config/dwmblocks && sudo make install
cd ~/.config/xmenu && sudo make install
