#!/bin/bash

export bar=#282C34
fg=$bar

export vol_ic_fg=$fg
export vol_ic_bg=#E06C75
export vol_fg=$vol_ic_bg
export vol_bg=$bar

export cpu_ic_fg=$fg
export cpu_ic_bg=#98C379
export cpu_fg=$cpu_ic_bg
export cpu_bg=$bar

export mem_ic_fg=$fg
export mem_ic_bg=#E5C07B
export mem_fg=$mem_ic_bg
export mem_bg=$bar

export storage_ic_fg=$fg
export storage_ic_bg=#61AFEF
export storage_fg=$storage_ic_bg
export storage_bg=$bar

export time_ic_fg=$fg
export time_ic_bg=#C678DD
export time_fg=$time_ic_bg
export time_bg=$bar

export date_ic_fg=$fg
export date_ic_bg=#56B6C2
export date_fg=$date_ic_bg
export date_bg=$bar

export uptime_ic_fg=$fg
export uptime_ic_bg=#ABB2BF
export uptime_fg=$uptime_ic_bg
export uptime_bg=$bar