#!/bin/bash

export bg=#282C34
export fg=#ABB2BF
export alt_fg=#D19A66

export error=#BE5046
export success=#98C379
export info=#61AFEF

export vol_ic_fg=$bg
export vol_ic_bg=#E06C75
export vol_fg=$vol_ic_bg
export vol_bg=$bg

export cpu_ic_fg=$bg
export cpu_ic_bg=#98C379
export cpu_fg=$cpu_ic_bg
export cpu_bg=$bg

export mem_ic_fg=$bg
export mem_ic_bg=#E5C07B
export mem_fg=$mem_ic_bg
export mem_bg=$bg

export storage_ic_fg=$bg
export storage_ic_bg=#61AFEF
export storage_fg=$storage_ic_bg
export storage_bg=$bg

export time_ic_fg=$bg
export time_ic_bg=#C678DD
export time_fg=$time_ic_bg
export time_bg=$bg

export date_ic_fg=$bg
export date_ic_bg=#56B6C2
export date_fg=$date_ic_bg
export date_bg=$bg