/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_systray.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fsignal.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "pertag.c"
#include "placemouse.c"
#include "push.c"
#include "restartsig.c"
#include "tab.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_fibonacci.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

