#!/bin/bash

shutdown() {
  systemctl poweroff
}

reboot() {
  systemctl reboot
}

suspend() {
  systemctl suspend
}

logout() {
  systemctl restart ly.service
}

get_options() {
  echo -en "Shutdown\0icon\x1fsystem-shutdown\n"
  echo -en "Reboot\0icon\x1fsystem-reboot\n"
  echo -en "Suspend\0icon\x1fsystem-suspend\n"
  echo -en "Logout\0icon\x1fsystem-log-out\n"
}

if [ x"$*" = x"Shutdown" ]; then
  shutdown
elif [ x"$*" = x"Reboot" ]; then
  reboot
elif [ x"$*" = x"Suspend" ]; then
  suspend
elif [ x"$*" = x"Logout" ]; then
  logout
fi

get_options
