#!/bin/bash

sudo ln -s  ~/dotfiles/usr/share/xsessions/ /usr/share/xsessions
ln -s ~/dotfiles/.config/* ~/.config/

sudo cp -srf ~/dotfiles/etc/pacman.conf /etc/
cp -srf ~/dotfiles/.Xresources ~/.Xresources
cp -srf ~/dotfiles/.fehbg ~/.fehbg